### ISSUE TITLE
[Build Bug] mismatched types:  found a different `StoreKey`

### ISSUE THREAD

**Issue by mikedotexe** [near/near-api-rs#12]
### What & Why?

Fix `cargo build`

### Definition of Done

cargo build with no error

### Resources & Additional Notes

![Screenshot 2024-11-16 at 2 52 45 PM](https://github.com/user-attachments/assets/aa848d63-b3db-40c5-9f2e-076a7fefd7d4)

### Priority

🟡 P2 : Medium

**Comment by akorchyn** [comment]
I highly suggest using the version defined in crates.io.
Meanwhile you can .into() it.

I want to remove dependency to near-* crates in the public api. This why I started maintaining a copy of the structs :)

**Comment by akorchyn** [comment]
Oopsie, I misunderstood the issue. It's fixed now :)
