### ISSUE TITLE
[Task] Add all functionallity from `Contract` to `Account`

### ISSUE THREAD

**Issue by gagdiez** [near/near-api-rs#17]
### Background

NEAR API JS has a similar interface for `Contracts`, which users tend to find confusing and hard to extend. Based on our experience in support, users understand better how to generalize to multiple contracts:

```
Account.function_call(contract_id, method)
```

than:

```
Contract.function_call(method)
```

For this exact reason is that we changed our docs in the past to stop using the `Contract` object, and simply show how to instantiate an `Account` and use it

After this, we stop getting questions about how to easily communicate with multiple contracts.

### User Story

- [ ] As a user, I want to use my account to interact with multiple contracts, without having to instantiate multiple objects

### Acceptance Criteria

The `Account` object can do all the actions that an account can:
- [ ] account.deploy()
- [ ] account.call_function()
- [ ] account.delete()
- [ ] ...

**Comment by akorchyn** [comment]
Hey, thanks for creating this issue. You raise a good point worth considering. However, I tend to favor separating account management (e.g., NEAR, keys, etc.) from contract interaction. Even though it's a single entity, it seems logical to distinguish between the two.

I agree that we could add the function call at the account level, but it wouldn't be very helpful in this case. The account doesn't hold anything that would simplify the process. Signing is abstracted and performed a bit later.

**Comment by gagdiez** [comment]
As a member of the Developer Relations team, I would kindly ask you to consider adding the ability to call functions and deploy contracts directly from the `Account` object

My feedback comes from giving support to the community, seeing how they use our APIs, and the common errors that many of them encounter

**Comment by frol** [comment]
This API is informed by near.cli.rs design and I have never heard anyone complaining about the “contract” vs “account” menus.

Contract object in near-api-js was terrible since it required a signer account upfront, even though it doesn’t need it for view-function calls and many other cases. Also, it had magical methods automatically generated that were hard to discover.

@gagdiez I am reluctant to overload Account object with more methods as that will create “too many options to choose from” problem. “Contract” follows the “function_call” pattern you mentioned, so the only difference is that you like it under Account name. Let’s ask real users of the library what they think

**Comment by akorchyn** [comment]
Yeah, I don't mind to have that. We might just wrap contract invocation in Account. 
Will keep Contract though

**Comment by gagdiez** [comment]
@frol I would prefer if we follow the way `workspaces-rs` works, which better reflects real world interactions: you task accounts with calling functions in contracts 

Specially if you need to interact with multiple contracts, with the current implementation you are forced to instantiate multiple contracts, when the important actions come from the account

The current logic to deploy a contract is weird as well, you instantiate a contract and then deploy on it. Feels more natural to create an account, deploy a contract in it, and then use any account to interact with it

But I agree, let's ask the community for feedback here

**Comment by gagdiez** [comment]
I'll close this PR until we have a clearer idea on how to make `near-api-js` and `near-api-rs` more homogeneous

**Comment by AlexKushnir1** [comment]
As I am relatively new user of the NEAR tools I am aware that near-workspaces-rs API is sincere intuitive one. It`s quite obviously to have an `Account` object that has ability to deploy and iteract with contract. Regarding the view methods, it seems we need to have option to call it without a signature and might make sense to keep a `Contract` object but design an `Account` as the top layout
