### ISSUE TITLE
Crate name in README

### ISSUE THREAD

**Issue by Sliman4** [near/near-api-rs#6]
The crate name is `near-api` on crates.io, but in README it's `near-rs` and the repo is named `near-api-rs`, would be bad if someone creates a crate with these names with private key stealer in build.rs

**Comment by akorchyn** [comment]
I agree that the `near-rs` should be replaced with the `near-api` in the README file.

The repository follows the standard (see `near-cli-rs`, `near-sdk-rs`, etc) to separate with JS and other implementations (`near-api-js`).
